### ISSUE TITLE
Explain why

### ISSUE THREAD

**Issue by jacwright** [Rainrider/rollup-plugin-workbox-build#1]
In your readme you share _what_ the only difference is between this plugin and the original. You don't explain _why_ that is important or why I would choose this project over the other. I would like to know why it is important.

Thanks!!

**Comment by Rainrider** [comment]
Sorry for the late reply. Workbox build picks the files from disk, `writeBundle` is the right hook for that.

From [rollup documentation](https://rollupjs.org/guide/en/)
> generateBundle
Type: (options: OutputOptions, bundle: { [fileName: string]: AssetInfo | ChunkInfo }, isWrite: boolean) => void
Kind: async, sequential
>
>Called at the end of bundle.generate() or immediately before the files are written in bundle.write(). To modify the files after they have been written, use the writeBundle hook. bundle provides the full list of files being written or generated along with their details:

**Comment by jacwright** [comment]
I appreciate the added info, but I still don't full understand why. Sorry for being slow here.

It this change added because the plugin doesn't work with `generateBundle` at all? Or is it because the files, in some cases, can be changed before `writeBundle`, so it is best to wait? Or is it purely a semantic thing the bugged you when you looked at the code?

And if this is the only change, should it be contributed back to the main branch to fix the error?

**Comment by frederikhors** [comment]
@jacwright IMO `writeBundle` is better than `generateBundle`. But if you don't modify files after all steps don't worry.

**Comment by Rainrider** [comment]
@jacwright 
When generateBundle is fired, the bundle has not been written to disk yet, so Workbox will either get your old files or none at all if you clean up your build destination before the build.

> And if this is the only change, should it be contributed back to the main branch to fix the error?

I did open a pull request over at gitlab where the original repo is, however no one responded to it, so I figured the project was abandoned.

**Comment by jacwright** [comment]
Thank you!

**Comment by frederikhors** [comment]
> I did open a pull request over at gitlab where the original repo is, however no one responded to it, so I figured the project was abandoned.

Let's make this the official project.
