### ISSUE TITLE
ValidationError: child "swDest" fails because ["swDest" is required]

### ISSUE THREAD

**Issue by frederikhors** [Rainrider/rollup-plugin-workbox-build#4]
`ValidationError: child "swDest" fails because ["swDest" is required]`

But here I can read https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin:

```
swDest | Optional String, defaulting to 'service-worker.js'
```

My config:

```js
workbox({
  mode: 'injectManifest',
  options: {
    swDest: 'service-worker.js',
    globDirectory: 'dist',
    swSrc: './public/service-worker.js'
  }
})
```

**Comment by Rainrider** [comment]
You should follow the [documentation for workbox-build](https://developers.google.com/web/tools/workbox/modules/workbox-build#injectmanifest_mode), **not** for workbox-webpack-plugin. Other than that it seems like you should swap the values of `swSrc` and `swDest`,
