### ISSUE TITLE
Unable to find a place to inject the manifest. Please ensure that your service worker file contains the following:/(\.precacheAndRoute\()\s*\[\s*\]\s*(\)|,)/

### ISSUE THREAD

**Issue by frederikhors** [Rainrider/rollup-plugin-workbox-build#5]
`AssertionError [ERR_ASSERTION]: Unable to find a place to inject the manifest. Please ensure that your service worker file contains the following:/(\.precacheAndRoute\()\s*\[\s*\]\s*(\)|,)/`

But I'm using this in my `service-worker.js`:

```
if ('workbox' in self) {
  workbox.precaching.precacheAndRoute(self.__precacheManifest || [])
}
```

and this in `rollup.config.js`:

```
workbox({
  mode: 'injectManifest',
  options: {
    swDest: 'service-worker.js',
    globDirectory: 'dist',
    swSrc: './public/service-worker.js'
  }
})
```

**Comment by Rainrider** [comment]
This is not related to the rollup-plugin.
