### ISSUE TITLE
It doesn't inject | generate workbox-cdn | disk js files

### ISSUE THREAD

**Issue by frederikhors** [Rainrider/rollup-plugin-workbox-build#7]
Using webpack analogue plugin it injects this below code in my `sw.js` file:

```js
importScripts("precache-manifest.8ac1ab3d48b09615967cc1035f9d25e.js", "https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");
```

Maybe this is a `workbox-build` 4 news?

**Comment by Rainrider** [comment]
Everything this plugin does is telling workbox-build that your rollup bundle has been written to disk and passing your options to it.
